name: 'company_x'
version: '1.0.0'

profile: 'company_x'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  company_x:
    raw:
      +schema: raw
      +materialized: view
    
    staging:
      +schema: staging
      +materialized: view

    transform:
      +schema: transform
      +materialized: table

    reporting:
      +schema: reporting
      +materialized: table
